### ISSUE TITLE
xo bundle generate

### ISSUE THREAD

**Issue by coryodaniel** [massdriver-cloud/xo#19]
This would be in the package `bundles` under `src/bundles`.

Generates a bundle. This would replace the [yeoman generator](https://github.com/colony-corp/massdriver-bundles/tree/main/generators/generator-massdriver/generators/app) in massdriver-bundles and free us of node in massdriver-bundles.

`xo bundle generate my-bundle-name --template-dir=./template --bundle-dir=./bundles`

* --template-dir is optional, default to `./xo-bundle-template`
* --bundle-dir is optional, default to `./bundles/`

I would suggest [promptui](https://github.com/manifoldco/promptui) or [go-prompt](https://github.com/c-bata/go-prompt)

This should generate:
* [ ] BUNDLE_DIR/my-bundle-name/
* [ ] BUNDLE_DIR/my-bundle-name/bundle.yaml # This will be the shorthand file
* [ ] BUNDLE_DIR/my-bundle-name/README.md # existing template in the yeoman generator
* [ ] BUNDLE_DIR/my-bundle-name/terraform/ # existing directory template exists in yeoman generator
* [ ] BUNDLE_DIR/my-bundle-name/schema.stories.js # existing template in the yeoman generator

bundle.yaml template:

```yaml
# This file will is used to generate all of the schema-*.json files in a bundle
# The root section will be the schema, uuid, title, description for all three schema-*.json files
schema: draft-07
#$id is auto generated based on folder name and {conn,input,arti} below
uuid: FC2C7101-86A6-437B-B8C2-A2391FE8C847
title: "<%= name %>"
description: <%= desc %>

#- everything above is replicated for each of the three keys below and suffixed w the key -artifacts, etc
#- below is the yaml form of the JSON Schema... with special processing to replace the string artifact://
#- with a {"$ref": 'path/to/the/conn.json'}

# Each key here down is a schema-*.json file JSON Schema equivalent
# schema-connections.json
connections:
  properties:
    default: artifact://aws-example

# schema-artifacts.json
artifacts:
  items:
    anyOf:
      - artifact://aws-example
      - artifact://aws-example

# schema-inputs.json
inputs:
  allOf:
    - artifact://aws-example1
    - artifact://aws-example2
```
